//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElasticTweets.Library.UnitTests.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TestFileContents {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestFileContents() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElasticTweets.Library.UnitTests.Resources.TestFileContents", typeof(TestFileContents).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grailbird.data.tweets_2009_02 = 
        /// [ {
        ///  &quot;source&quot; : &quot;web&quot;,
        ///  &quot;entities&quot; : {
        ///    &quot;user_mentions&quot; : [ ],
        ///    &quot;media&quot; : [ ],
        ///    &quot;hashtags&quot; : [ ],
        ///    &quot;urls&quot; : [ ]
        ///  },
        ///  &quot;geo&quot; : {
        ///  },
        ///  &quot;id_str&quot; : &quot;1234567890&quot;,
        ///  &quot;text&quot; : &quot;Dummy Tweet 1&quot;,
        ///  &quot;id&quot; : 1234567890,
        ///  &quot;created_at&quot; : &quot;Fri Feb 27 16:23:07 +0000 2009&quot;,
        ///  &quot;user&quot; : {
        ///    &quot;name&quot; : &quot;Dummy Name&quot;,
        ///    &quot;screen_name&quot; : &quot;ElasticTweetsUnitTest&quot;,
        ///    &quot;protected&quot; : false,
        ///    &quot;id_str&quot; : &quot;12345678&quot;,
        ///    &quot;profile_image_url_https&quot; : &quot;&quot;,
        ///    &quot;id&quot; : 12345678,
        ///    &quot;veri [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TwoTweets {
            get {
                return ResourceManager.GetString("TwoTweets", resourceCulture);
            }
        }
    }
}
